#!/bin/sh

../.venv/bin/python3 .githooks/pre-commit.py

# Check the exit status of the Python script
if [ $? -ne 0 ]; then
    echo "Pre-commit script failed. Aborting commit."
    exit 1
fi

echo "Pre-commit script completed successfully."
exit 0